services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      - INTERNAL_API_URL=http://backend:8080
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      public:

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
      args:
        BUILD_TAGS: ${BUILD_TAGS:-}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable'
      SSC_SEED_DATABASE: ${SSC_SEED_DATABASE}
      SSC_SEED_CASBIN_CSV: ${SSC_SEED_CASBIN_CSV}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      CSRF_SECRET: ${CSRF_SECRET}
      SSC_SITE_NAME: ${SSC_SITE_NAME}
      SSC_PUBLIC_URL: ${SSC_PUBLIC_URL}
      SSC_REGISTRATION_ENABLED: ${SSC_REGISTRATION_ENABLED}
      SSC_DEBUG_ENABLED: ${SSC_DEBUG_ENABLED}
      SSC_ADMIN_PASSWORD: ${SSC_ADMIN_PASSWORD}
      SSC_LICENSE_KEY: ${SSC_LICENSE_KEY}
      SSC_API_PREFIX: /api
      SSO_GITHUB_CLIENT_ID: ${SSO_GITHUB_CLIENT_ID}
      SSO_GITHUB_CLIENT_SECRET: ${SSO_GITHUB_CLIENT_SECRET}
      SSO_GITLAB_CLIENT_ID: ${SSO_GITLAB_CLIENT_ID}
      SSO_GITLAB_CLIENT_SECRET: ${SSO_GITLAB_CLIENT_SECRET}
      SSO_GITLAB_BASE_URL: ${SSO_GITLAB_BASE_URL}
      SSO_OIDC_CLIENT_ID: ${SSO_OIDC_CLIENT_ID}
      SSO_OIDC_CLIENT_SECRET: ${SSO_OIDC_CLIENT_SECRET}
      SSO_OIDC_ISSUER_URL: ${SSO_OIDC_ISSUER_URL}
      SSO_OIDC_SCOPES: ${SSO_OIDC_SCOPES}
    networks:
      public:
      private:

  db:
    container_name: db
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION:-17}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      private:

  caddy:
    container_name: caddy
    restart: unless-stopped
    hostname: servasec.local
    build:
      context: caddy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    networks:
      public:
      private:

volumes:
  postgres_data:
  caddy_data:

networks:
  public:
    driver: bridge
    ipam:
      config:
        - subnet: 172.70.1.0/24
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 172.70.2.0/24
