apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servasec.backendName" . }}
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servasec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "servasec.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "servasec.fullname" . }}
            - secretRef:
                name: {{ include "servasec.fullname" . }}
          env:
            - name: DATABASE_URL
              value: {{ include "servasec.databaseUrl" . | quote }}
            - name: SSC_SEED_DATABASE
              value: "true"
            - name: SSC_SEED_CASBIN_CSV
              value: "true"
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
