{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "servasec.fullname" . }}-backend
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "servasec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "servasec.selectorLabels" . | nindent 16 }}
              app.kubernetes.io/component: frontend
      ports:
        - port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "servasec.selectorLabels" . | nindent 16 }}
              app.kubernetes.io/component: postgresql
      ports:
        - port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "servasec.fullname" . }}-frontend
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "servasec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
  ingress: []
---
{{- if .Values.postgresql.internal }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "servasec.fullname" . }}-postgresql
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "servasec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "servasec.selectorLabels" . | nindent 16 }}
              app.kubernetes.io/component: backend
      ports:
        - port: 5432
{{- end }}
{{- end }}
