{{- if .Values.postgresql.internal }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "servasec.postgresqlName" . }}
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "servasec.postgresqlName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "servasec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "servasec.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image | quote }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "servasec.fullname" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "servasec.fullname" . }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "servasec.fullname" . }}
                  key: POSTGRES_DB
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresql.user | quote }}]
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresql.user | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.storageSize | default "10Gi" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "servasec.postgresqlName" . }}
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "servasec.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
