apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servasec.fullname" . }}
  labels:
    {{- include "servasec.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | default .Values.postgresql.password | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  REFRESH_SECRET: {{ .Values.secrets.refreshSecret | quote }}
  CSRF_SECRET: {{ .Values.secrets.csrfSecret | quote }}
  SSC_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  SSC_LICENSE_KEY: {{ .Values.secrets.licenseKey | quote }}
  SSO_GITHUB_CLIENT_ID: {{ .Values.secrets.sso.githubClientId | quote }}
  SSO_GITHUB_CLIENT_SECRET: {{ .Values.secrets.sso.githubClientSecret | quote }}
  SSO_GITLAB_CLIENT_ID: {{ .Values.secrets.sso.gitlabClientId | quote }}
  SSO_GITLAB_CLIENT_SECRET: {{ .Values.secrets.sso.gitlabClientSecret | quote }}
  SSO_GITLAB_BASE_URL: {{ .Values.secrets.sso.gitlabBaseUrl | quote }}
  SSO_OIDC_CLIENT_ID: {{ .Values.secrets.sso.oidcClientId | quote }}
  SSO_OIDC_CLIENT_SECRET: {{ .Values.secrets.sso.oidcClientSecret | quote }}
  SSO_OIDC_ISSUER_URL: {{ .Values.secrets.sso.oidcIssuerUrl | quote }}
  SSO_OIDC_SCOPES: {{ .Values.secrets.sso.oidcScopes | quote }}
